site_name: Homelab Docs
# site_url: "https://dgalanberasaluce.github.io/" #  http://localhost:8080/
copyright: Copyright (©) 2026 David Galan
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime
  # features:
    # - navigation.top
    # - navigation.tabs
    # - search.suggest
    # - search.highlight

repo_url: "https://dgalanberasaluce.github.io"
repo_name: "Home"

# Menú extra para volver al Jekyll principal
# nav:
  # - Home: index.md
  # - Servers: servidores.md

plugins: []
  # - search: false 

extra_css: []
# - stylesheets/extra.css

extra_javascript: []
# - javascripts/force_home.js