site_name: Homelab Docs
# site_url: "https://dgalanberasaluce.github.io/" #  http://localhost:8080/
copyright: Copyright (Â©) 2026 David Galan
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime

repo_url: "https://dgalanberasaluce.github.io"
repo_name: "Home"

plugins:
- glightbox

extra_css: []

extra_javascript: []

markdown_extensions:
  - attr_list     